version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 4 8 * *"
      timezone: "Europe/Vienna"
    assignees:
      - "sengels-tum"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 4 1 * *"
      timezone: "Europe/Vienna"
    assignees:
      - "sengels-tum"
