version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "06:00"
      timezone: "Europe/Vienna"
    assignees:
      - "sengels-tum"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "00:30"
      timezone: "Europe/Vienna"
    assignees:
      - "sengels-tum"
